
package localhost._8888;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AsyncImplService", targetNamespace = "http://localhost:8888/", wsdlLocation = "http://localhost:8888/?wsdl")
public class AsyncImplService
    extends Service
{

    private final static URL ASYNCIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ASYNCIMPLSERVICE_EXCEPTION;
    private final static QName ASYNCIMPLSERVICE_QNAME = new QName("http://localhost:8888/", "AsyncImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ASYNCIMPLSERVICE_WSDL_LOCATION = url;
        ASYNCIMPLSERVICE_EXCEPTION = e;
    }

    public AsyncImplService() {
        super(__getWsdlLocation(), ASYNCIMPLSERVICE_QNAME);
    }

    public AsyncImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ASYNCIMPLSERVICE_QNAME, features);
    }

    public AsyncImplService(URL wsdlLocation) {
        super(wsdlLocation, ASYNCIMPLSERVICE_QNAME);
    }

    public AsyncImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ASYNCIMPLSERVICE_QNAME, features);
    }

    public AsyncImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AsyncImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AsyncImpl
     */
    @WebEndpoint(name = "AsyncImplPort")
    public AsyncImpl getAsyncImplPort() {
        return super.getPort(new QName("http://localhost:8888/", "AsyncImplPort"), AsyncImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AsyncImpl
     */
    @WebEndpoint(name = "AsyncImplPort")
    public AsyncImpl getAsyncImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8888/", "AsyncImplPort"), AsyncImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ASYNCIMPLSERVICE_EXCEPTION!= null) {
            throw ASYNCIMPLSERVICE_EXCEPTION;
        }
        return ASYNCIMPLSERVICE_WSDL_LOCATION;
    }

}
